CC=gcc
CFLAGS=-Werror -Wall -pedantic -std=gnu99 -g
LDFLAGS=-pthread -lrt -lm

TARGET_EXEC ?= manager.out

BUILD_DIR ?= ./build/main
SRC_DIRS ?= ./src ../shared_memory

SRCS := $(shell find $(SRC_DIRS) -name *.c)
OBJS := $(SRCS:%=$(BUILD_DIR)/%.o)
DEPS := $(OBJS:.o=.d)

INC_DIRS := $(shell find $(SRC_DIRS) -type d)
INC_FLAGS := $(addprefix -I,$(INC_DIRS))

CPPFLAGS ?= $(INC_FLAGS) -MMD -MP

../$(TARGET_EXEC): $(OBJS)
	$(CC) $(OBJS) -o $@ $(LDFLAGS)

# c source
$(BUILD_DIR)/%.c.o: %.c
	$(MKDIR_P) $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

.PHONY: clean

clean:
	$(RM) -r ./build

-include $(DEPS)

MKDIR_P ?= mkdir -p